export const links=[
    {
        id:1,
        url:'/About',
        text:"About",
        classList:"header-nav__item",
        classLink:"header-nav__link"
    },
    {
        id:2,
        url:'/Experience',
        text:"Experience",
        classList:"header-nav__item",
        classLink:"header-nav__link"
    },
    {
        id:3,
        url:'/Work',
        text:"Work",
        classList:"header-nav__item",
        classLink:"header-nav__link"
    },
    {
        id:4,
        url:'/Contact',
        text:"Contact",
        classList:"header-nav__item",
        classLink:"header-nav__link"
    },
    {
        id:5,
        url:'/Resume',
        text:"Resume",
        classList:"header-nav__btn",
        classLink:"header-nav__cta"
    },

]